### ISSUE TITLE
Warning errors

### ISSUE THREAD

**Issue by MustafaAmer-1** [AbdeltwabMF/nxprayer#19]
The build fails due to `-Werror` parameter used in the Makefile as there is many warnings in [src/np_main.cpp](https://github.com/AbdeltwabMF/next-prayer/blob/main/src/np_main.cpp) file.
here is the make command log output
```bash
Cleaning...
rm -f np_main
Cleaning done. 

Compiling the source code...
sed -i "s|IAMUName|/home/mustafa|" src/np_main.cpp
g++ -Wall -Wextra -Werror -std=c++2a -pedantic -O3 -DNDEBUG -o np_main src/*.cpp
src/np_main.cpp: In function ‘void File(const char*)’:
src/np_main.cpp:89:39: error: ignoring return value of ‘FILE* freopen(const char*, const char*, FILE*)’, declared with attribute warn_unused_result [-Werror=unused-result]
   89 | void File(const char *fread) { freopen(fread, "r", stdin); }
      |                                ~~~~~~~^~~~~~~~~~~~~~~~~~~
src/np_main.cpp: In function ‘void ReadData()’:
src/np_main.cpp:204:11: error: ignoring return value of ‘int system(const char*)’, declared with attribute warn_unused_result [-Werror=unused-result]
  204 |     system("np_fetch.py");
      |     ~~~~~~^~~~~~~~~~~~~~~
cc1plus: all warnings being treated as errors
make: *** [Makefile:40: np_main] Error 1
```

**Comment by AbdeltwabMF** [comment]
Could you please provide what version of g++ you are using?

**Comment by AbdeltwabMF** [comment]
I am using `gcc version 11.2.0 (GCC)` and it produces no errors at all.
So, I'm assuming your version of `gcc` is outdated!

![image](https://user-images.githubusercontent.com/55063723/160779637-6ae49bbc-b442-4d02-9099-f3e4f5b97016.png)

But since it is useful only for debugging purposes, I'm gonna remove it. #20 

----

Thank you for your contribution 💗

**Comment by AbdeltwabMF** [comment]
#20
