### ISSUE TITLE
Wrong times

### ISSUE THREAD

**Issue by alkhaldieid** [AbdeltwabMF/nxprayer#21]
The program works but gives wrong times.
Also, AUR build doesn't run Artix linux.

**Comment by AbdeltwabMF** [comment]
Have you changed the location in np_config.py file?

**Comment by alkhaldieid** [comment]
After updating the np_config.py and make all clean install, I got different times but they are off by 25 minutes. The problem could be caused by the url where the data are fetched from not the program, but I am not sure. I will look at it later and let you know.

**Comment by AbdeltwabMF** [comment]
Maybe the calculation method is set to egyption authority(5) rather than calculation method used in your country?

**Comment by alkhaldieid** [comment]
That is true. Thank you very much.
