### ISSUE TITLE
kde

### ISSUE THREAD

**Issue by ahmed-tasaly** [AbdeltwabMF/nxprayer#23]
can you add this to kde plasma ?

**Comment by AbdeltwabMF** [comment]
Customizing the window manager status bar is far easier than customizing the desktop environment status bar. From that capacity, we choose to design the tool specifically for the tiling window managers. 
If you would, search how to add a script output to the status bar of kde.

[This may help](https://github.com/wsdfhjxc/do-it-yourself-bar)
