### ISSUE TITLE
Error when building from source

### ISSUE THREAD

**Issue by AmroAbdul** [AbdeltwabMF/nxprayer#27]
**when tried to build from source:**
```
cp -f np_main /home/amro/.local/bin/
cp: cannot stat 'np_main': No such file or directory
make: *** [Makefile:52: install] Error 1
```
![2022-11-02_00-39](https://user-images.githubusercontent.com/104640155/199347470-8f30222d-0be1-402f-b68f-f2c7b3a989c7.png)

**Comment by AbdeltwabMF** [comment]
What command do you use?

**Comment by AbdeltwabMF** [comment]
There is an error in the command in `README` file
the command should be:

```bash
make all install clean
```

NOT
```bash
make all clean install
```

**Comment by AbdeltwabMF** [comment]
I'm sorry for the late response.
