### ISSUE TITLE
The App Suddenly stopped working giving me "Unable to read data"

### ISSUE THREAD

**Issue by mostafa20220** [AbdeltwabMF/nxprayer#28]
**Describe the bug**
The App Suddenly stopped working giving me The following:
"Unable to read data"
"Run "make all clean install" first!"

I tried running the command: 
"Run "make all clean install"
Returned this: 
"make: *** No rule to make target 'all'.  Stop."

I tried removing the software and installing again, didn't work.

**To Reproduce**
Just run it from the terminal.

**Screenshots**
![image](https://user-images.githubusercontent.com/95468778/210161942-d4065db8-5ba4-465d-9726-7a8cfa966182.png)

**Desktop (please complete the following information):**
 - OS: Arch Linux x86_64
 - Kernel: 6.1.1-arch1-1 
 - Version:  v0.3.0.r2.a45fa61-1

**Comment by ahr9n** [comment]
Hi, Mostafa. Try the following commands:
```sh
docker build -t next-prayer .
docker run --rm next-prayer next-prayer --version
```
If it gave you the installed version correctly, it should be fine. 

Then, use `next-prayer` options with _docker_ as follows:
```sh
docker run --rm next-prayer next-prayer [options...]
```

**Comment by AbdeltwabMF** [comment]
@mostafa20220 

Try run:

```bash
np_fetch.py
```

**Comment by mostafa20220** [comment]
@AbdeltwabMF 
Okay, here is the result...
![image](https://user-images.githubusercontent.com/95468778/210317575-9ef85b22-c4e8-46e2-a3fc-0c4d858b1904.png)

**Comment by mostafa20220** [comment]
@ahr9n
I am using the AUR version not a Docker image 
I have never used docker before

However, I installed docker and run those commands but...
![image](https://user-images.githubusercontent.com/95468778/210321067-6b49282d-a89c-440e-8de3-29a4be9dac20.png)

And I downloaded the next-prayer image, created a new container, and run the image but...
![image](https://user-images.githubusercontent.com/95468778/210321526-5ad2b43c-5ab7-4689-88f9-e0989793c5de.png)

**Comment by AbdeltwabMF** [comment]
@mostafa20220 
I think you need the `requests` package to be able to run the script
try `python -m pip install requests`

**Comment by AbdeltwabMF** [comment]
In a future release Insha Allah it will be automated to fetch a new year.

**Comment by mostafa20220** [comment]
@AbdeltwabMF 
**Thank You**. It worked.

I run these:
`python -m pip install requests`
`np_fetch.py`

**screenshot**:
![image](https://user-images.githubusercontent.com/95468778/211164706-e50390e8-2741-49f4-97a5-428b89a65b3d.png)
![image](https://user-images.githubusercontent.com/95468778/211164715-a138b76a-7324-449a-956e-2828a5114f2f.png)
