### ISSUE TITLE
Error during building from source and installing from AUR

### ISSUE THREAD

**Issue by emcho99** [AbdeltwabMF/nxprayer#39]
After running the command ```make all install``` or installing using AUR i get the error message:
```make: *** No rule to make target 'all'.  Stop.```

**Comment by AbdeltwabMF** [comment]
The main branch is not deployable right now, consider downloading from [release page](https://github.com/AbdeltwabMF/next-prayer/releases/tag/v0.3.0) and build the package using 
```shell
make all install clean
```

**Comment by samyosm** [comment]
Even by downloading from the release page I get the following:
```
Could not fetch data
make: *** [Makefile:51: install] Error 1
```

**Comment by emcho99** [comment]
@samyosm Yup, can confirm that after trying to install the 0.3.0 release I get the same error message.

**Comment by samyosm** [comment]
Could it be the API service not working anymore?

**Comment by AbdeltwabMF** [comment]
I apologize for the inconvenience caused. It has been identified that there is a typo in the config file. The corrected line should be:
```python
    "year": f"{date.today().year}", 
```
instead of
```python
    "year": f"${date.today().year}",
```

---

**Kindly inform me if you come across any problems.**

**Comment by emcho99** [comment]
@AbdeltwabMF Thank you! I was actually looking exactly at this line of code and thought something isn't right. 
After correcting the line it installs successfully and works good.

![image](https://user-images.githubusercontent.com/103337610/229329835-26b4a2c4-95b3-4a12-965d-59ef58fb084f.png)

Thanks for the support!
